// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_middleware.ts";
import * as $1 from "./routes/api/joke.ts";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/posts.tsx";
import * as $4 from "./routes/user/account.tsx";
import * as $5 from "./routes/user/confirm_register.tsx";
import * as $6 from "./routes/user/login.tsx";
import * as $7 from "./routes/user/logout.tsx";
import * as $8 from "./routes/user/post/[id].tsx";
import * as $9 from "./routes/user/register.tsx";
import * as $$0 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/_middleware.ts": $0,
    "./routes/api/joke.ts": $1,
    "./routes/index.tsx": $2,
    "./routes/posts.tsx": $3,
    "./routes/user/account.tsx": $4,
    "./routes/user/confirm_register.tsx": $5,
    "./routes/user/login.tsx": $6,
    "./routes/user/logout.tsx": $7,
    "./routes/user/post/[id].tsx": $8,
    "./routes/user/register.tsx": $9,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
